"use client";

import { useState } from "react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { runDraft } from "@/features/writing/actions";
import type {
  ContentPlan,
  Draft,
  DraftStatus,
  ResearchBrief,
  Trend,
} from "@/generated/prisma/client";

const STATUS_VARIANT: Record<
  DraftStatus,
  "default" | "secondary" | "destructive"
> = {
  PENDING: "secondary",
  PROCESSING: "secondary",
  COMPLETED: "default",
  FAILED: "destructive",
};

const STATUS_LABEL: Record<DraftStatus, string> = {
  PENDING: "Pending",
  PROCESSING: "Processing",
  COMPLETED: "Completed",
  FAILED: "Failed",
};

export function WritingQueue({
  items,
}: {
  items: (ContentPlan & {
    research: ResearchBrief & { trend: Trend };
    draft: Draft | null;
  })[];
}) {
  const [pendingId, setPendingId] = useState<string | null>(null);
  const [errors, setErrors] = useState<Record<string, string>>({});

  async function handleRun(planId: string) {
    setPendingId(planId);
    setErrors((prev) => ({ ...prev, [planId]: "" }));
    const result = await runDraft(planId);
    setPendingId(null);
    if ("error" in result) {
      setErrors((prev) => ({ ...prev, [planId]: result.error }));
    }
  }

  if (items.length === 0) {
    return (
      <p className="text-muted-foreground text-sm">
        No completed content plans yet. Plan a completed research brief on
        the{" "}
        <a href="/planning" className="underline underline-offset-4">
          Planning
        </a>{" "}
        page first.
      </p>
    );
  }

  return (
    <div className="grid gap-3">
      {items.map((plan) => {
        const draft = plan.draft;
        const isRunning = pendingId === plan.id;
        const buttonLabel = !draft
          ? "Write draft"
          : draft.status === "FAILED"
            ? "Retry"
            : "Rewrite";

        return (
          <Card key={plan.id}>
            <CardHeader className="flex-row items-start justify-between gap-2">
              <div>
                <CardTitle className="flex items-center gap-2">
                  {plan.research.trend.topic}
                  {draft && (
                    <Badge variant={STATUS_VARIANT[draft.status]}>
                      {STATUS_LABEL[draft.status]}
                    </Badge>
                  )}
                </CardTitle>
                <CardDescription>
                  {plan.format} · {plan.selectedAngle}
                </CardDescription>
              </div>
              <Button
                size="sm"
                variant={draft?.status === "FAILED" ? "outline" : "default"}
                disabled={isRunning || draft?.status === "PROCESSING"}
                onClick={() => handleRun(plan.id)}
              >
                {isRunning ? "Writing..." : buttonLabel}
              </Button>
            </CardHeader>
            <CardContent
              className={
                errors[plan.id] ||
                draft?.status === "FAILED" ||
                draft?.status === "COMPLETED"
                  ? "flex flex-col gap-3"
                  : "hidden"
              }
            >
              {errors[plan.id] && (
                <p className="text-destructive text-sm">{errors[plan.id]}</p>
              )}
              {draft?.status === "FAILED" && draft.errorMessage && (
                <p className="text-destructive text-sm">
                  Last attempt failed: {draft.errorMessage}
                </p>
              )}
              {draft?.status === "COMPLETED" && (
                <div className="flex flex-col gap-3 text-sm">
                  {draft.content && (
                    <p className="whitespace-pre-wrap">{draft.content}</p>
                  )}
                  {draft.slides.length > 0 && (
                    <div className="grid gap-2">
                      {draft.slides.map((slide, i) => (
                        <div key={i} className="rounded-lg border p-3">
                          <p className="text-muted-foreground mb-1 text-xs font-medium">
                            Slide {i + 1}
                          </p>
                          <p className="whitespace-pre-wrap">{slide}</p>
                        </div>
                      ))}
                    </div>
                  )}
                  {draft.hashtags.length > 0 && (
                    <p className="text-muted-foreground">
                      {draft.hashtags.map((h) => `#${h}`).join(" ")}
                    </p>
                  )}
                  <p className="text-muted-foreground text-xs">
                    Generated by {draft.provider} ({draft.model}) ·{" "}
                    {draft.attempts} attempt{draft.attempts === 1 ? "" : "s"}
                  </p>
                </div>
              )}
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}
